In [1]:
import pandas as pd
import numpy as np
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline
from sklearn.neural_network import MLPClassifier
from sklearn import metrics
from sklearn.metrics import classification_report,confusion_matrix
import matplotlib.pyplot as plt  
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from collections import defaultdict
from xgboost import XGBClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import KFold

data = pd.read_csv('study-breast-cancer-wisconsin.csv')
data.head()


ClumpThickness   UniformityOfCellSize  UniformityOfCellShape   \
0                5                     1                       1   
1                5                     4                       4   
2                3                     1                       1   
3                6                     8                       8   
4                4                     1                       1   

   MarginalAdhesion  SingleEpithelialCellSize  BareNuclei  BlandChromatin  \
0                 1                         2         1.0               3   
1                 5                         7        10.0               3   
2                 1                         2         2.0               3   
3                 1                         3         4.0               3   
4                 3                         2         1.0               3   

   NormalNucleoli  Mitoses  Class  
0               1        1      2  
1               2        1      2  
2               1        1      2  
3               7        1      2  
4               1        1      2

In [2]:
data.describe()

ClumpThickness   UniformityOfCellSize  UniformityOfCellShape   \
count       699.000000            699.000000              699.000000   
mean          4.417740              3.134478                3.207439   
std           2.815741              3.051459                2.971913   
min           1.000000              1.000000                1.000000   
25%           2.000000              1.000000                1.000000   
50%           4.000000              1.000000                1.000000   
75%           6.000000              5.000000                5.000000   
max          10.000000             10.000000               10.000000   

       MarginalAdhesion  SingleEpithelialCellSize  BareNuclei  BlandChromatin  \
count        699.000000                699.000000  683.000000      699.000000   
mean           2.806867                  3.216023    3.544656        3.437768   
std            2.855379                  2.214300    3.643857        2.438364   
min            1.000000                  1.000000    1.000000        1.000000   
25%            1.000000                  2.000000    1.000000        2.000000   
50%            1.000000                  2.000000    1.000000        3.000000   
75%            4.000000                  4.000000    6.000000        5.000000   
max           10.000000                 10.000000   10.000000       10.000000   

       NormalNucleoli     Mitoses       Class  
count      699.000000  699.000000  699.000000  
mean         2.866953    1.589413    2.689557  
std          3.053634    1.715078    0.951273  
min          1.000000    1.000000    2.000000  
25%          1.000000    1.000000    2.000000  
50%          1.000000    1.000000    2.000000  
75%          4.000000    1.000000    4.000000  
max         10.000000   10.000000    4.000000

In [3]:
data.shape

(699, 10)

In [4]:
#handle missing values
data= data.fillna(data.mean())

In [5]:
# Shuffle the data
data = shuffle(data) 

label = data.pop("Class")

X=data
Y=label

In [6]:
kf = KFold(n_splits=10, shuffle=True)
datadistO = defaultdict(int) # int() produces 0
for a in Y:
    datadistO[a] += 1
print("Origional Data Distribution", datadistO)

Origional Data Distribution defaultdict(<class 'int'>, {4: 241, 2: 458})


In [7]:
mlp = MLPClassifier(hidden_layer_sizes=(50,30,40,50,30),max_iter=4200)
i=1
for train, test in kf.split(X):
    print("\n\nEvaluation on Fold # ", i)
    X_train = X.iloc[train]
    X_test =  X.iloc[test]
    y_train = Y.iloc[train]
    y_test = Y.iloc[test]
    
    #convert array into dataframe
    X_train=pd.DataFrame(X_train, columns=list(X.columns))
    y_train=pd.DataFrame(y_train)
    
    datadistTr = defaultdict(int) # int() produces 0
    for a in y_train:
        datadistTr[a] += 1
    print("\nTrain Data Distribution", datadistTr)
    datadistTe = defaultdict(int) # int() produces 0
    for a in y_test:
        datadistTe[a] += 1
    print("\nTest Data Distribution", datadistTe)
    
    mlp.fit(X_train,y_train)
    
    P_nn = mlp.predict(X_test)
    P_nnt = mlp.predict(X_train)
    
    print("\nTraining Accuracy:",metrics.accuracy_score(y_train, P_nnt))
    print("\nTest Accuracy:",metrics.accuracy_score(y_test, P_nn))
    
    cm = confusion_matrix(y_test,P_nn)
    print("\nConfusion Matrix:\n",cm)
    
    print("Training Classification Report:\n",classification_report(y_train,P_nnt))
    print("\nTesting Classification Report:\n",classification_report(y_test,P_nn))
    
    i = i + 1



Evaluation on Fold #  1

Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {2: 41, 4: 29})


C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)



Training Accuracy: 0.9904610492845787

Test Accuracy: 1.0

Confusion Matrix:
 [[41  0]
 [ 0 29]]
Training Classification Report:
               precision    recall  f1-score   support

           2       0.99      0.99      0.99       417
           4       0.99      0.99      0.99       212

   micro avg       0.99      0.99      0.99       629
   macro avg       0.99      0.99      0.99       629
weighted avg       0.99      0.99      0.99       629


Testing Classification Report:
               precision    recall  f1-score   support

           2       1.00      1.00      1.00        41
           4       1.00      1.00      1.00        29

   micro avg       1.00      1.00      1.00        70
   macro avg       1.00      1.00      1.00        70
weighted avg       1.00      1.00      1.00        70



Evaluation on Fold #  2

Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {4: 30, 2: 40})


C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)



Training Accuracy: 0.9952305246422893

Test Accuracy: 0.9428571428571428

Confusion Matrix:
 [[39  1]
 [ 3 27]]
Training Classification Report:
               precision    recall  f1-score   support

           2       0.99      1.00      1.00       418
           4       1.00      0.99      0.99       211

   micro avg       1.00      1.00      1.00       629
   macro avg       1.00      0.99      0.99       629
weighted avg       1.00      1.00      1.00       629


Testing Classification Report:
               precision    recall  f1-score   support

           2       0.93      0.97      0.95        40
           4       0.96      0.90      0.93        30

   micro avg       0.94      0.94      0.94        70
   macro avg       0.95      0.94      0.94        70
weighted avg       0.94      0.94      0.94        70



Evaluation on Fold #  3

Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {4: 22, 2: 48})


C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)



Training Accuracy: 0.9984101748807631

Test Accuracy: 0.9714285714285714

Confusion Matrix:
 [[46  2]
 [ 0 22]]
Training Classification Report:
               precision    recall  f1-score   support

           2       1.00      1.00      1.00       410
           4       1.00      1.00      1.00       219

   micro avg       1.00      1.00      1.00       629
   macro avg       1.00      1.00      1.00       629
weighted avg       1.00      1.00      1.00       629


Testing Classification Report:
               precision    recall  f1-score   support

           2       1.00      0.96      0.98        48
           4       0.92      1.00      0.96        22

   micro avg       0.97      0.97      0.97        70
   macro avg       0.96      0.98      0.97        70
weighted avg       0.97      0.97      0.97        70



Evaluation on Fold #  4

Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {2: 44, 4: 26})


C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)



Training Accuracy: 0.9936406995230525

Test Accuracy: 0.9428571428571428

Confusion Matrix:
 [[42  2]
 [ 2 24]]
Training Classification Report:
               precision    recall  f1-score   support

           2       1.00      0.99      1.00       414
           4       0.99      1.00      0.99       215

   micro avg       0.99      0.99      0.99       629
   macro avg       0.99      0.99      0.99       629
weighted avg       0.99      0.99      0.99       629


Testing Classification Report:
               precision    recall  f1-score   support

           2       0.95      0.95      0.95        44
           4       0.92      0.92      0.92        26

   micro avg       0.94      0.94      0.94        70
   macro avg       0.94      0.94      0.94        70
weighted avg       0.94      0.94      0.94        70



Evaluation on Fold #  5

Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {4: 21, 2: 49})


C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)



Training Accuracy: 1.0

Test Accuracy: 0.9571428571428572

Confusion Matrix:
 [[47  2]
 [ 1 20]]
Training Classification Report:
               precision    recall  f1-score   support

           2       1.00      1.00      1.00       409
           4       1.00      1.00      1.00       220

   micro avg       1.00      1.00      1.00       629
   macro avg       1.00      1.00      1.00       629
weighted avg       1.00      1.00      1.00       629


Testing Classification Report:
               precision    recall  f1-score   support

           2       0.98      0.96      0.97        49
           4       0.91      0.95      0.93        21

   micro avg       0.96      0.96      0.96        70
   macro avg       0.94      0.96      0.95        70
weighted avg       0.96      0.96      0.96        70



Evaluation on Fold #  6

Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {2: 50, 4: 20})


C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)



Training Accuracy: 0.9920508744038156

Test Accuracy: 0.9714285714285714

Confusion Matrix:
 [[49  1]
 [ 1 19]]
Training Classification Report:
               precision    recall  f1-score   support

           2       1.00      0.99      0.99       408
           4       0.99      0.99      0.99       221

   micro avg       0.99      0.99      0.99       629
   macro avg       0.99      0.99      0.99       629
weighted avg       0.99      0.99      0.99       629


Testing Classification Report:
               precision    recall  f1-score   support

           2       0.98      0.98      0.98        50
           4       0.95      0.95      0.95        20

   micro avg       0.97      0.97      0.97        70
   macro avg       0.96      0.96      0.97        70
weighted avg       0.97      0.97      0.97        70



Evaluation on Fold #  7

Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {2: 39, 4: 31})


C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)



Training Accuracy: 0.9952305246422893

Test Accuracy: 0.8857142857142857

Confusion Matrix:
 [[37  2]
 [ 6 25]]
Training Classification Report:
               precision    recall  f1-score   support

           2       1.00      1.00      1.00       419
           4       1.00      0.99      0.99       210

   micro avg       1.00      1.00      1.00       629
   macro avg       1.00      0.99      0.99       629
weighted avg       1.00      1.00      1.00       629


Testing Classification Report:
               precision    recall  f1-score   support

           2       0.86      0.95      0.90        39
           4       0.93      0.81      0.86        31

   micro avg       0.89      0.89      0.89        70
   macro avg       0.89      0.88      0.88        70
weighted avg       0.89      0.89      0.88        70



Evaluation on Fold #  8

Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {2: 47, 4: 23})


C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)



Training Accuracy: 1.0

Test Accuracy: 0.9428571428571428

Confusion Matrix:
 [[44  3]
 [ 1 22]]
Training Classification Report:
               precision    recall  f1-score   support

           2       1.00      1.00      1.00       411
           4       1.00      1.00      1.00       218

   micro avg       1.00      1.00      1.00       629
   macro avg       1.00      1.00      1.00       629
weighted avg       1.00      1.00      1.00       629


Testing Classification Report:
               precision    recall  f1-score   support

           2       0.98      0.94      0.96        47
           4       0.88      0.96      0.92        23

   micro avg       0.94      0.94      0.94        70
   macro avg       0.93      0.95      0.94        70
weighted avg       0.95      0.94      0.94        70



Evaluation on Fold #  9

Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {2: 51, 4: 19})


C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)



Training Accuracy: 0.9904610492845787

Test Accuracy: 0.9428571428571428

Confusion Matrix:
 [[48  3]
 [ 1 18]]
Training Classification Report:
               precision    recall  f1-score   support

           2       0.99      1.00      0.99       407
           4       0.99      0.98      0.99       222

   micro avg       0.99      0.99      0.99       629
   macro avg       0.99      0.99      0.99       629
weighted avg       0.99      0.99      0.99       629


Testing Classification Report:
               precision    recall  f1-score   support

           2       0.98      0.94      0.96        51
           4       0.86      0.95      0.90        19

   micro avg       0.94      0.94      0.94        70
   macro avg       0.92      0.94      0.93        70
weighted avg       0.95      0.94      0.94        70



Evaluation on Fold #  10

Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {2: 49, 4: 20})


C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)



Training Accuracy: 0.9888888888888889

Test Accuracy: 0.9855072463768116

Confusion Matrix:
 [[48  1]
 [ 0 20]]
Training Classification Report:
               precision    recall  f1-score   support

           2       0.99      0.99      0.99       409
           4       0.98      0.99      0.98       221

   micro avg       0.99      0.99      0.99       630
   macro avg       0.99      0.99      0.99       630
weighted avg       0.99      0.99      0.99       630


Testing Classification Report:
               precision    recall  f1-score   support

           2       1.00      0.98      0.99        49
           4       0.95      1.00      0.98        20

   micro avg       0.99      0.99      0.99        69
   macro avg       0.98      0.99      0.98        69
weighted avg       0.99      0.99      0.99        69



In [8]:
svmL = SVC(kernel='linear')  
print("\t\tSVM with linear Kernal\n")
i=1
for train, test in kf.split(X):
    print("\n\nEvaluation on Fold # ", i)
    
    X_train = X.iloc[train]
    X_test =  X.iloc[test]
    y_train = Y.iloc[train]
    y_test = Y.iloc[test]
   
    
    #convert array into dataframe
    X_train=pd.DataFrame(X_train, columns=list(X.columns))
    y_train=pd.DataFrame(y_train)
    
    datadistTr = defaultdict(int) # int() produces 0
    for a in y_train:
        datadistTr[a] += 1
    print("\nTrain Data Distribution", datadistTr)
    datadistTe = defaultdict(int) # int() produces 0
    for a in y_test:
        datadistTe[a] += 1
    print("\nTest Data Distribution", datadistTe)
    
    svmL.fit(X_train, y_train)
    
    P_svm1 = svmL.predict(X_test)
    P_svm1t = svmL.predict(X_train)
    
    print("Training Accuracy:",metrics.accuracy_score(y_train, P_svm1t))
    print("Test Accuracy:",metrics.accuracy_score(y_test, P_svm1))

    cm = confusion_matrix(y_test,P_svm1)
    print("Confusion Matrix:\n",cm)
    
    print("Training Classification Report:\n",classification_report(y_train,P_svm1t))
    print("\nTesting Classification Report:\n",classification_report(y_test,P_svm1))
    
    i = i + 1

		SVM with linear Kernal



Evaluation on Fold #  1

Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {2: 51, 4: 19})
Training Accuracy: 0.972972972972973
Test Accuracy: 0.9571428571428572
Confusion Matrix:
 [[49  2]
 [ 1 18]]
Training Classification Report:
               precision    recall  f1-score   support

           2       0.98      0.98      0.98       407
           4       0.96      0.96      0.96       222

   micro avg       0.97      0.97      0.97       629
   macro avg       0.97      0.97      0.97       629
weighted avg       0.97      0.97      0.97       629


Testing Classification Report:
               precision    recall  f1-score   support

           2       0.98      0.96      0.97        51
           4       0.90      0.95      0.92        19

   micro avg       0.96      0.96      0.96        70
   macro avg       0.94      0.95      0.95        70
weighted avg       0.96      0.96      0.

C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,


Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {4: 19, 2: 51})
Training Accuracy: 0.972972972972973
Test Accuracy: 0.9428571428571428
Confusion Matrix:
 [[48  3]
 [ 1 18]]
Training Classification Report:
               precision    recall  f1-score   support

           2       0.98      0.98      0.98       407
           4       0.96      0.96      0.96       222

   micro avg       0.97      0.97      0.97       629
   macro avg       0.97      0.97      0.97       629
weighted avg       0.97      0.97      0.97       629


Testing Classification Report:
               precision    recall  f1-score   support

           2       0.98      0.94      0.96        51
           4       0.86      0.95      0.90        19

   micro avg       0.94      0.94      0.94        70
   macro avg       0.92      0.94      0.93        70
weighted avg       0.95      0.94      0.94        70



Evaluation on Fold #  7

Train Data 

C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,

In [9]:
svmRBF = SVC()
print("\t\tSVM with RBF Kernal\n")
i=1
for train, test in kf.split(X):
    print("\n\nEvaluation on Fold # ", i)
    
    X_train = X.iloc[train]
    X_test =  X.iloc[test]
    y_train = Y.iloc[train]
    y_test = Y.iloc[test]

    #convert array into dataframe
    X_train=pd.DataFrame(X_train, columns=list(X.columns))
    y_train=pd.DataFrame(y_train)
    
    datadistTr = defaultdict(int) # int() produces 0
    for a in y_train:
        datadistTr[a] += 1
    print("\nTrain Data Distribution", datadistTr)
    datadistTe = defaultdict(int) # int() produces 0
    for a in y_test:
        datadistTe[a] += 1
    print("\nTest Data Distribution", datadistTe)
    
    svmRBF.fit(X_train, y_train)  
    
    P_svmRBF = svmRBF.predict(X_test)
    P_svmRBFt = svmRBF.predict(X_train)
    
    print("Training Accuracy:",metrics.accuracy_score(y_train, P_svmRBFt))
    print("Test Accuracy:",metrics.accuracy_score(y_test, P_svmRBF))

    cm = confusion_matrix(y_test,P_svmRBF)
    print("Confusion Matrix:\n",cm)
    
    print("Training Classification Report:\n",classification_report(y_train,P_svmRBFt))
    print("\nTesting Classification Report:\n",classification_report(y_test,P_svmRBF))
    
    i = i + 1

		SVM with RBF Kernal



Evaluation on Fold #  1

Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {2: 47, 4: 23})


C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


Training Accuracy: 0.9968203497615262
Test Accuracy: 0.9571428571428572
Confusion Matrix:
 [[44  3]
 [ 0 23]]
Training Classification Report:
               precision    recall  f1-score   support

           2       1.00      1.00      1.00       411
           4       1.00      1.00      1.00       218

   micro avg       1.00      1.00      1.00       629
   macro avg       1.00      1.00      1.00       629
weighted avg       1.00      1.00      1.00       629


Testing Classification Report:
               precision    recall  f1-score   support

           2       1.00      0.94      0.97        47
           4       0.88      1.00      0.94        23

   micro avg       0.96      0.96      0.96        70
   macro avg       0.94      0.97      0.95        70
weighted avg       0.96      0.96      0.96        70



Evaluation on Fold #  2

Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {4: 24, 2: 46})
Training Ac

C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.2

Test Accuracy: 0.9428571428571428
Confusion Matrix:
 [[38  4]
 [ 0 28]]
Training Classification Report:
               precision    recall  f1-score   support

           2       1.00      1.00      1.00       416
           4       1.00      1.00      1.00       213

   micro avg       1.00      1.00      1.00       629
   macro avg       1.00      1.00      1.00       629
weighted avg       1.00      1.00      1.00       629



C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)



Testing Classification Report:
               precision    recall  f1-score   support

           2       1.00      0.90      0.95        42
           4       0.88      1.00      0.93        28

   micro avg       0.94      0.94      0.94        70
   macro avg       0.94      0.95      0.94        70
weighted avg       0.95      0.94      0.94        70



Evaluation on Fold #  6

Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {2: 44, 4: 26})
Training Accuracy: 0.9984101748807631
Test Accuracy: 0.9714285714285714
Confusion Matrix:
 [[42  2]
 [ 0 26]]
Training Classification Report:
               precision    recall  f1-score   support

           2       1.00      1.00      1.00       414
           4       1.00      1.00      1.00       215

   micro avg       1.00      1.00      1.00       629
   macro avg       1.00      1.00      1.00       629
weighted avg       1.00      1.00      1.00       629


Testing Cl

C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.2

Test Accuracy: 0.9565217391304348
Confusion Matrix:
 [[46  3]
 [ 0 20]]
Training Classification Report:
               precision    recall  f1-score   support

           2       1.00      0.99      1.00       409
           4       0.99      1.00      0.99       221

   micro avg       0.99      0.99      0.99       630
   macro avg       0.99      0.99      0.99       630
weighted avg       0.99      0.99      0.99       630


Testing Classification Report:
               precision    recall  f1-score   support

           2       1.00      0.94      0.97        49
           4       0.87      1.00      0.93        20

   micro avg       0.96      0.96      0.96        69
   macro avg       0.93      0.97      0.95        69
weighted avg       0.96      0.96      0.96        69



In [10]:
KNN = KNeighborsClassifier(n_neighbors=3, metric='minkowski', p=2)
print("\t\tK-NN Classification\n")
i=1
for train, test in kf.split(X):
    print("\n\nEvaluation on Fold # ", i)
    
    X_train = X.iloc[train]
    X_test =  X.iloc[test]
    y_train = Y.iloc[train]
    y_test = Y.iloc[test]
   
    #convert array into dataframe
    X_train=pd.DataFrame(X_train, columns=list(X.columns))
    y_train=pd.DataFrame(y_train)
    
    datadistTr = defaultdict(int) # int() produces 0
    for a in y_train:
        datadistTr[a] += 1
    print("\nTrain Data Distribution", datadistTr)
    datadistTe = defaultdict(int) # int() produces 0
    for a in y_test:
        datadistTe[a] += 1
    print("\nTest Data Distribution", datadistTe)
    
    KNN.fit(X_train, y_train)  
    
    Pknn = KNN.predict(X_test)
    Pknnt = KNN.predict(X_train)

    print("Training Accuracy:",metrics.accuracy_score(y_train, Pknnt))
    print("Test Accuracy:",metrics.accuracy_score(y_test, Pknn))

    cm = confusion_matrix(y_test,Pknn)
    print("Confusion Matrix:\n",cm)
    
    print("Training Classification Report:\n",classification_report(y_train,Pknnt))
    print("\nTesting Classification Report:\n",classification_report(y_test,Pknn))
    
    i = i + 1

C:\Users\Ayesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().


		K-NN Classification



Evaluation on Fold #  1

Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {2: 54, 4: 16})
Training Accuracy: 0.9777424483306836
Test Accuracy: 1.0
Confusion Matrix:
 [[54  0]
 [ 0 16]]
Training Classification Report:
               precision    recall  f1-score   support

           2       0.99      0.98      0.98       404
           4       0.96      0.98      0.97       225

   micro avg       0.98      0.98      0.98       629
   macro avg       0.97      0.98      0.98       629
weighted avg       0.98      0.98      0.98       629


Testing Classification Report:
               precision    recall  f1-score   support

           2       1.00      1.00      1.00        54
           4       1.00      1.00      1.00        16

   micro avg       1.00      1.00      1.00        70
   macro avg       1.00      1.00      1.00        70
weighted avg       1.00      1.00      1.00        70



E

C:\Users\Ayesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
C:\Users\Ayesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
C:\Users\Ayesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
C:\Users\Ayesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
C:\Users\Ayesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: DataConversionWarning: A c

Test Accuracy: 0.9857142857142858
Confusion Matrix:
 [[47  1]
 [ 0 22]]
Training Classification Report:
               precision    recall  f1-score   support

           2       0.99      0.98      0.98       410
           4       0.96      0.99      0.97       219

   micro avg       0.98      0.98      0.98       629
   macro avg       0.97      0.98      0.98       629
weighted avg       0.98      0.98      0.98       629


Testing Classification Report:
               precision    recall  f1-score   support

           2       1.00      0.98      0.99        48
           4       0.96      1.00      0.98        22

   micro avg       0.99      0.99      0.99        70
   macro avg       0.98      0.99      0.98        70
weighted avg       0.99      0.99      0.99        70



Evaluation on Fold #  6

Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {4: 18, 2: 52})
Training Accuracy: 0.9809220985691574
Test Accura

C:\Users\Ayesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
C:\Users\Ayesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
C:\Users\Ayesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
C:\Users\Ayesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().


In [11]:
# Fitting Decision tree classifier to the Training set
DTC = DecisionTreeClassifier(criterion='entropy')

print("\t\t Decision tree classifier\n")
i=1
for train, test in kf.split(X):
    print("\n\nEvaluation on Fold # ", i)
    
    X_train = X.iloc[train]
    X_test =  X.iloc[test]
    y_train = Y.iloc[train]
    y_test = Y.iloc[test]
    
    #convert array into dataframe
    X_train=pd.DataFrame(X_train, columns=list(X.columns))
    y_train=pd.DataFrame(y_train)
    
    datadistTr = defaultdict(int) # int() produces 0
    for a in y_train:
        datadistTr[a] += 1
    print("\nTrain Data Distribution", datadistTr)
    datadistTe = defaultdict(int) # int() produces 0
    for a in y_test:
        datadistTe[a] += 1
    print("\nTest Data Distribution", datadistTe)
    
    DTC.fit(X_train, y_train)  
    
    P_DT = DTC.predict(X_test)
    P_DTt = DTC.predict(X_train)
    
    print("Training Accuracy:",metrics.accuracy_score(y_train, P_DTt))
    print("Test Accuracy:",metrics.accuracy_score(y_test, P_DT))

    cm = confusion_matrix(y_test,P_DT)
    print("Confusion Matrix:\n",cm)
    
    print("Training Classification Report:\n",classification_report(y_train,P_DTt))
    print("\nTesting Classification Report:\n",classification_report(y_test,P_DT))
    
    i = i + 1

		 Decision tree classifier



Evaluation on Fold #  1

Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {4: 20, 2: 50})
Training Accuracy: 1.0
Test Accuracy: 0.9142857142857143
Confusion Matrix:
 [[46  4]
 [ 2 18]]
Training Classification Report:
               precision    recall  f1-score   support

           2       1.00      1.00      1.00       408
           4       1.00      1.00      1.00       221

   micro avg       1.00      1.00      1.00       629
   macro avg       1.00      1.00      1.00       629
weighted avg       1.00      1.00      1.00       629


Testing Classification Report:
               precision    recall  f1-score   support

           2       0.96      0.92      0.94        50
           4       0.82      0.90      0.86        20

   micro avg       0.91      0.91      0.91        70
   macro avg       0.89      0.91      0.90        70
weighted avg       0.92      0.91      0.92        7

In [12]:
LRC = LogisticRegression(random_state=0)
print("\t\t Logistic Regression \n")
i=1
for train, test in kf.split(X):
    print("\n\nEvaluation on Fold # ", i)
    
    X_train = X.iloc[train]
    X_test =  X.iloc[test]
    y_train = Y.iloc[train]
    y_test = Y.iloc[test]
    
    #convert array into dataframe
    X_train=pd.DataFrame(X_train, columns=list(X.columns))
    y_train=pd.DataFrame(y_train)
    
    datadistTr = defaultdict(int) # int() produces 0
    for a in y_train:
        datadistTr[a] += 1
    print("\nTrain Data Distribution", datadistTr)
    datadistTe = defaultdict(int) # int() produces 0
    for a in y_test:
        datadistTe[a] += 1
    print("\nTest Data Distribution", datadistTe)
    
    LRC.fit(X_train, y_train)  
    
    P_LR = LRC.predict(X_test)
    P_LRt = LRC.predict(X_train)
        
    print("Training Accuracy:",metrics.accuracy_score(y_train, P_LRt))
    print("Test Accuracy:",metrics.accuracy_score(y_test, P_LR))

    cm = confusion_matrix(y_test,P_LR)
    print("Confusion Matrix:\n",cm)
    
    print("Training Classification Report:\n",classification_report(y_train,P_LRt))
    print("\nTesting Classification Report:\n",classification_report(y_test,P_LR))
    
    i = i + 1

		 Logistic Regression 



Evaluation on Fold #  1

Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {4: 21, 2: 49})
Training Accuracy: 0.9650238473767886
Test Accuracy: 0.9571428571428572
Confusion Matrix:
 [[49  0]
 [ 3 18]]
Training Classification Report:
               precision    recall  f1-score   support

           2       0.97      0.98      0.97       409
           4       0.95      0.95      0.95       220

   micro avg       0.97      0.97      0.97       629
   macro avg       0.96      0.96      0.96       629
weighted avg       0.96      0.97      0.96       629


Testing Classification Report:
               precision    recall  f1-score   support

           2       0.94      1.00      0.97        49
           4       1.00      0.86      0.92        21

   micro avg       0.96      0.96      0.96        70
   macro avg       0.97      0.93      0.95        70
weighted avg       0.96      0.96      0.

C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\li

              precision    recall  f1-score   support

           2       1.00      0.98      0.99        44
           4       0.96      1.00      0.98        26

   micro avg       0.99      0.99      0.99        70
   macro avg       0.98      0.99      0.98        70
weighted avg       0.99      0.99      0.99        70



Evaluation on Fold #  6

Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {2: 43, 4: 27})
Training Accuracy: 0.9682034976152624
Test Accuracy: 0.9285714285714286
Confusion Matrix:
 [[41  2]
 [ 3 24]]
Training Classification Report:
               precision    recall  f1-score   support

           2       0.97      0.98      0.98       415
           4       0.96      0.95      0.95       214

   micro avg       0.97      0.97      0.97       629
   macro avg       0.97      0.96      0.96       629
weighted avg       0.97      0.97      0.97       629


Testing Classification Report:
            

C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\li

In [13]:
NBC = GaussianNB()
print("\t\tNaive Bayes \n")
i=1
for train, test in kf.split(X):
    print("\nEvaluation on Fold # ", i)
    
    X_train = X.iloc[train]
    X_test =  X.iloc[test]
    y_train = Y.iloc[train]
    y_test = Y.iloc[test]
    
    #convert array into dataframe
    X_train=pd.DataFrame(X_train, columns=list(X.columns))
    y_train=pd.DataFrame(y_train)
    
    datadistTr = defaultdict(int) # int() produces 0
    for a in y_train:
        datadistTr[a] += 1
    print("\nTrain Data Distribution", datadistTr)
    datadistTe = defaultdict(int) # int() produces 0
    for a in y_test:
        datadistTe[a] += 1
    print("\nTest Data Distribution", datadistTe)
    
    NBC.fit(X_train, y_train)  
    
    P_NB = NBC.predict(X_test)
    P_NBt = NBC.predict(X_train)
    
    print("Training Accuracy:",metrics.accuracy_score(y_train, P_NBt))
    print("Test Accuracy:",metrics.accuracy_score(y_test, P_NB))

    cm = confusion_matrix(y_test,P_NB)
    print("Confusion Matrix:\n",cm)
   
    print("Training Classification Report:\n",classification_report(y_train,P_NBt))
    print("\nTesting Classification Report:\n",classification_report(y_test,P_NB))
    
    i = i + 1

		Naive Bayes 


Evaluation on Fold #  1

Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {4: 23, 2: 47})
Training Accuracy: 0.9554848966613673
Test Accuracy: 0.9857142857142858
Confusion Matrix:
 [[46  1]
 [ 0 23]]
Training Classification Report:
               precision    recall  f1-score   support

           2       0.98      0.95      0.97       411
           4       0.91      0.97      0.94       218

   micro avg       0.96      0.96      0.96       629
   macro avg       0.95      0.96      0.95       629
weighted avg       0.96      0.96      0.96       629


Testing Classification Report:
               precision    recall  f1-score   support

           2       1.00      0.98      0.99        47
           4       0.96      1.00      0.98        23

   micro avg       0.99      0.99      0.99        70
   macro avg       0.98      0.99      0.98        70
weighted avg       0.99      0.99      0.99        

C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,


Evaluation on Fold #  7

Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {2: 45, 4: 25})
Training Accuracy: 0.9570747217806042
Test Accuracy: 0.9857142857142858
Confusion Matrix:
 [[44  1]
 [ 0 25]]
Training Classification Report:
               precision    recall  f1-score   support

           2       0.98      0.95      0.97       413
           4       0.91      0.97      0.94       216

   micro avg       0.96      0.96      0.96       629
   macro avg       0.95      0.96      0.95       629
weighted avg       0.96      0.96      0.96       629


Testing Classification Report:
               precision    recall  f1-score   support

           2       1.00      0.98      0.99        45
           4       0.96      1.00      0.98        25

   micro avg       0.99      0.99      0.99        70
   macro avg       0.98      0.99      0.98        70
weighted avg       0.99      0.99      0.99        70


Evaluation 

C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [14]:
# Fitting Random Forest classifier to the Training set
classifier = RandomForestClassifier(n_estimators=10, criterion='entropy', random_state=0)
print("\t\tRandom Forest Classification \n")
i=1
for train, test in kf.split(X):
    print("\nEvaluation on Fold # ", i)
    
    X_train = X.iloc[train]
    X_test =  X.iloc[test]
    y_train = Y.iloc[train]
    y_test = Y.iloc[test]
    
    #convert array into dataframe
    X_train=pd.DataFrame(X_train, columns=list(X.columns))
    y_train=pd.DataFrame(y_train)

    datadistTr = defaultdict(int) # int() produces 0
    for a in y_train:
        datadistTr[a] += 1
    print("\nTrain Data Distribution", datadistTr)
    datadistTe = defaultdict(int) # int() produces 0
    for a in y_test:
        datadistTe[a] += 1
    print("\nTest Data Distribution", datadistTe)
    
    classifier.fit(X_train, y_train)  
    
    P_RF = classifier.predict(X_test)
    P_RFt = classifier.predict(X_train)
    
    print("Training Accuracy:",metrics.accuracy_score(y_train, P_RFt))
    print("Test Accuracy:",metrics.accuracy_score(y_test, P_RF))

    cm = confusion_matrix(y_test,P_RF)
    print("Confusion Matrix:\n",cm)
    
    print("Training Classification Report:\n",classification_report(y_train,P_RFt))
    print("\nTesting Classification Report:\n",classification_report(y_test,P_RF))
    
    i = i + 1

		Random Forest Classification 


Evaluation on Fold #  1

Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {4: 26, 2: 44})
Training Accuracy: 0.9968203497615262
Test Accuracy: 0.9714285714285714
Confusion Matrix:
 [[42  2]
 [ 0 26]]


C:\Users\Ayesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:26: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
C:\Users\Ayesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:26: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().


Training Classification Report:
               precision    recall  f1-score   support

           2       1.00      1.00      1.00       414
           4       1.00      0.99      1.00       215

   micro avg       1.00      1.00      1.00       629
   macro avg       1.00      1.00      1.00       629
weighted avg       1.00      1.00      1.00       629


Testing Classification Report:
               precision    recall  f1-score   support

           2       1.00      0.95      0.98        44
           4       0.93      1.00      0.96        26

   micro avg       0.97      0.97      0.97        70
   macro avg       0.96      0.98      0.97        70
weighted avg       0.97      0.97      0.97        70


Evaluation on Fold #  2

Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {4: 30, 2: 40})
Training Accuracy: 1.0
Test Accuracy: 0.9857142857142858
Confusion Matrix:
 [[40  0]
 [ 1 29]]
Training Classification Rep

C:\Users\Ayesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:26: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().



Testing Classification Report:
               precision    recall  f1-score   support

           2       1.00      0.98      0.99        48
           4       0.96      1.00      0.98        22

   micro avg       0.99      0.99      0.99        70
   macro avg       0.98      0.99      0.98        70
weighted avg       0.99      0.99      0.99        70


Evaluation on Fold #  4

Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {4: 26, 2: 44})
Training Accuracy: 0.9984101748807631
Test Accuracy: 0.9428571428571428
Confusion Matrix:
 [[43  1]
 [ 3 23]]
Training Classification Report:
               precision    recall  f1-score   support

           2       1.00      1.00      1.00       414
           4       1.00      1.00      1.00       215

   micro avg       1.00      1.00      1.00       629
   macro avg       1.00      1.00      1.00       629
weighted avg       1.00      1.00      1.00       629


Testing Cla

C:\Users\Ayesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:26: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
C:\Users\Ayesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:26: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().


Test Accuracy: 0.9571428571428572
Confusion Matrix:
 [[46  3]
 [ 0 21]]
Training Classification Report:
               precision    recall  f1-score   support

           2       1.00      1.00      1.00       409
           4       1.00      1.00      1.00       220

   micro avg       1.00      1.00      1.00       629
   macro avg       1.00      1.00      1.00       629
weighted avg       1.00      1.00      1.00       629


Testing Classification Report:
               precision    recall  f1-score   support

           2       1.00      0.94      0.97        49
           4       0.88      1.00      0.93        21

   micro avg       0.96      0.96      0.96        70
   macro avg       0.94      0.97      0.95        70
weighted avg       0.96      0.96      0.96        70


Evaluation on Fold #  6

Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {4: 25, 2: 45})
Training Accuracy: 0.9968203497615262


C:\Users\Ayesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:26: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().


Test Accuracy: 0.9571428571428572
Confusion Matrix:
 [[44  1]
 [ 2 23]]
Training Classification Report:
               precision    recall  f1-score   support

           2       1.00      1.00      1.00       413
           4       1.00      1.00      1.00       216

   micro avg       1.00      1.00      1.00       629
   macro avg       1.00      1.00      1.00       629
weighted avg       1.00      1.00      1.00       629


Testing Classification Report:
               precision    recall  f1-score   support

           2       0.96      0.98      0.97        45
           4       0.96      0.92      0.94        25

   micro avg       0.96      0.96      0.96        70
   macro avg       0.96      0.95      0.95        70
weighted avg       0.96      0.96      0.96        70


Evaluation on Fold #  7

Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {2: 42, 4: 28})
Training Accuracy: 1.0
Test Accuracy: 0.9428571428

C:\Users\Ayesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:26: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
C:\Users\Ayesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:26: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().


Test Accuracy: 0.9714285714285714
Confusion Matrix:
 [[49  2]
 [ 0 19]]
Training Classification Report:
               precision    recall  f1-score   support

           2       1.00      1.00      1.00       407
           4       1.00      1.00      1.00       222

   micro avg       1.00      1.00      1.00       629
   macro avg       1.00      1.00      1.00       629
weighted avg       1.00      1.00      1.00       629


Testing Classification Report:
               precision    recall  f1-score   support

           2       1.00      0.96      0.98        51
           4       0.90      1.00      0.95        19

   micro avg       0.97      0.97      0.97        70
   macro avg       0.95      0.98      0.97        70
weighted avg       0.97      0.97      0.97        70


Evaluation on Fold #  9


C:\Users\Ayesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:26: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().



Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {2: 49, 4: 21})
Training Accuracy: 0.9936406995230525
Test Accuracy: 0.9857142857142858
Confusion Matrix:
 [[48  1]
 [ 0 21]]
Training Classification Report:
               precision    recall  f1-score   support

           2       1.00      1.00      1.00       409
           4       0.99      0.99      0.99       220

   micro avg       0.99      0.99      0.99       629
   macro avg       0.99      0.99      0.99       629
weighted avg       0.99      0.99      0.99       629


Testing Classification Report:
               precision    recall  f1-score   support

           2       1.00      0.98      0.99        49
           4       0.95      1.00      0.98        21

   micro avg       0.99      0.99      0.99        70
   macro avg       0.98      0.99      0.98        70
weighted avg       0.99      0.99      0.99        70


Evaluation on Fold #  10

Train Data

C:\Users\Ayesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:26: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().


In [16]:
model = XGBClassifier()
print("\t\tXGBoost \n")
i=1
for train, test in kf.split(X):
    print("\nEvaluation on Fold # ", i)
    
    X_train = X.iloc[train]
    X_test =  X.iloc[test]
    y_train = Y.iloc[train]
    y_test = Y.iloc[test]
    
    #convert array into dataframe
    X_train=pd.DataFrame(X_train, columns=list(X.columns))
    y_train=pd.DataFrame(y_train)
    
    #convert array into dataframe
    X_train=pd.DataFrame(X_train, columns=list(X.columns))
    y_train=pd.DataFrame(y_train)
    
    datadistTr = defaultdict(int) # int() produces 0
    for a in y_train:
        datadistTr[a] += 1
    print("\nTrain Data Distribution", datadistTr)
    datadistTe = defaultdict(int) # int() produces 0
    for a in y_test:
        datadistTe[a] += 1
    print("\nTest Data Distribution", datadistTe)
    
    model.fit(X_train, y_train)  
    
    print("model.feature_importances_:  ", model.feature_importances_)
    
    P_XGB = model.predict(X_test)
    P_XGBt = model.predict(X_train)
     
    print("Training Accuracy:",metrics.accuracy_score(y_train, P_XGBt))
    print("Test Accuracy:",metrics.accuracy_score(y_test, P_XGB))

    cm = confusion_matrix(y_test,P_XGB)
    print("Confusion Matrix:\n",cm)
       
    print("Training Classification Report:\n",classification_report(y_train,P_XGBt))
    print("\nTesting Classification Report:\n",classification_report(y_test,P_XGB))
    
    i = i + 1

		XGBoost 


Evaluation on Fold #  1

Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {2: 45, 4: 25})


C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:252: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


model.feature_importances_:   [0.15448852 0.1336117  0.05427975 0.11482254 0.06889353 0.22546972
 0.06680585 0.15031315 0.03131524]
Training Accuracy: 0.9888712241653418
Test Accuracy: 0.9428571428571428
Confusion Matrix:
 [[41  4]
 [ 0 25]]
Training Classification Report:
               precision    recall  f1-score   support

           2       1.00      0.99      0.99       413
           4       0.98      0.99      0.98       216

   micro avg       0.99      0.99      0.99       629
   macro avg       0.99      0.99      0.99       629
weighted avg       0.99      0.99      0.99       629


Testing Classification Report:
               precision    recall  f1-score   support

           2       1.00      0.91      0.95        45
           4       0.86      1.00      0.93        25

   micro avg       0.94      0.94      0.94        70
   macro avg       0.93      0.96      0.94        70
weighted avg       0.95      0.94      0.94        70


Evaluation on Fold #  2

Train Data D

In [17]:
bdt = AdaBoostClassifier(DecisionTreeClassifier(max_depth=1),algorithm="SAMME",n_estimators=200)
print("\t\tAdaboost \n")
i=1
for train, test in kf.split(X):
    print("\nEvaluation on Fold # ", i)
    
    X_train = X.iloc[train]
    X_test =  X.iloc[test]
    y_train = Y.iloc[train]
    y_test = Y.iloc[test]
    
    #convert array into dataframe
    X_train=pd.DataFrame(X_train, columns=list(X.columns))
    y_train=pd.DataFrame(y_train)
    
    #convert array into dataframe
    X_train=pd.DataFrame(X_train, columns=list(X.columns))
    y_train=pd.DataFrame(y_train)

    datadistTr = defaultdict(int) # int() produces 0
    for a in y_train:
        datadistTr[a] += 1
    print("\nTrain Data Distribution", datadistTr)
    datadistTe = defaultdict(int) # int() produces 0
    for a in y_test:
        datadistTe[a] += 1
    print("\nTest Data Distribution", datadistTe)
    
    bdt.fit(X_train, y_train)  
    
    P_Ada = bdt.predict(X_test)
    P_Adat = bdt.predict(X_train)
    
    print("Training Accuracy:",metrics.accuracy_score(y_train, P_Adat))
    print("Test Accuracy:",metrics.accuracy_score(y_test, P_Ada))

    cm = confusion_matrix(y_test,P_Ada)
    print("Confusion Matrix:\n",cm)
    
    print("Training Classification Report:\n",classification_report(y_train,P_Adat))
    print("\nTesting Classification Report:\n",classification_report(y_test,P_Ada))
    
    i = i + 1

		Adaboost 


Evaluation on Fold #  1

Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {4: 22, 2: 48})


C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Training Accuracy: 0.9809220985691574
Test Accuracy: 0.9428571428571428
Confusion Matrix:
 [[45  3]
 [ 1 21]]
Training Classification Report:
               precision    recall  f1-score   support

           2       0.99      0.98      0.99       410
           4       0.96      0.98      0.97       219

   micro avg       0.98      0.98      0.98       629
   macro avg       0.98      0.98      0.98       629
weighted avg       0.98      0.98      0.98       629


Testing Classification Report:
               precision    recall  f1-score   support

           2       0.98      0.94      0.96        48
           4       0.88      0.95      0.91        22

   micro avg       0.94      0.94      0.94        70
   macro avg       0.93      0.95      0.94        70
weighted avg       0.95      0.94      0.94        70


Evaluation on Fold #  2

Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {4: 16, 2: 54})


C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Training Accuracy: 0.985691573926868
Test Accuracy: 0.9142857142857143
Confusion Matrix:
 [[50  4]
 [ 2 14]]
Training Classification Report:
               precision    recall  f1-score   support

           2       0.99      0.99      0.99       404
           4       0.98      0.98      0.98       225

   micro avg       0.99      0.99      0.99       629
   macro avg       0.98      0.98      0.98       629
weighted avg       0.99      0.99      0.99       629


Testing Classification Report:
               precision    recall  f1-score   support

           2       0.96      0.93      0.94        54
           4       0.78      0.88      0.82        16

   micro avg       0.91      0.91      0.91        70
   macro avg       0.87      0.90      0.88        70
weighted avg       0.92      0.91      0.92        70


Evaluation on Fold #  3

Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {2: 41, 4: 29})


C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Training Accuracy: 0.9745627980922098
Test Accuracy: 0.9571428571428572
Confusion Matrix:
 [[41  0]
 [ 3 26]]
Training Classification Report:
               precision    recall  f1-score   support

           2       0.98      0.98      0.98       417
           4       0.97      0.96      0.96       212

   micro avg       0.97      0.97      0.97       629
   macro avg       0.97      0.97      0.97       629
weighted avg       0.97      0.97      0.97       629


Testing Classification Report:
               precision    recall  f1-score   support

           2       0.93      1.00      0.96        41
           4       1.00      0.90      0.95        29

   micro avg       0.96      0.96      0.96        70
   macro avg       0.97      0.95      0.96        70
weighted avg       0.96      0.96      0.96        70


Evaluation on Fold #  4

Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {2: 47, 4: 23})


C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Training Accuracy: 0.985691573926868
Test Accuracy: 0.9285714285714286
Confusion Matrix:
 [[43  4]
 [ 1 22]]
Training Classification Report:
               precision    recall  f1-score   support

           2       0.99      0.99      0.99       411
           4       0.98      0.98      0.98       218

   micro avg       0.99      0.99      0.99       629
   macro avg       0.98      0.98      0.98       629
weighted avg       0.99      0.99      0.99       629


Testing Classification Report:
               precision    recall  f1-score   support

           2       0.98      0.91      0.95        47
           4       0.85      0.96      0.90        23

   micro avg       0.93      0.93      0.93        70
   macro avg       0.91      0.94      0.92        70
weighted avg       0.93      0.93      0.93        70


Evaluation on Fold #  5

Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {4: 25, 2: 45})


C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Training Accuracy: 0.9825119236883942
Test Accuracy: 0.9714285714285714
Confusion Matrix:
 [[45  0]
 [ 2 23]]
Training Classification Report:
               precision    recall  f1-score   support

           2       0.99      0.98      0.99       413
           4       0.97      0.98      0.97       216

   micro avg       0.98      0.98      0.98       629
   macro avg       0.98      0.98      0.98       629
weighted avg       0.98      0.98      0.98       629


Testing Classification Report:
               precision    recall  f1-score   support

           2       0.96      1.00      0.98        45
           4       1.00      0.92      0.96        25

   micro avg       0.97      0.97      0.97        70
   macro avg       0.98      0.96      0.97        70
weighted avg       0.97      0.97      0.97        70


Evaluation on Fold #  6

Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {2: 45, 4: 25})


C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Training Accuracy: 0.9793322734499205
Test Accuracy: 0.9571428571428572
Confusion Matrix:
 [[43  2]
 [ 1 24]]
Training Classification Report:
               precision    recall  f1-score   support

           2       0.99      0.98      0.98       413
           4       0.97      0.97      0.97       216

   micro avg       0.98      0.98      0.98       629
   macro avg       0.98      0.98      0.98       629
weighted avg       0.98      0.98      0.98       629


Testing Classification Report:
               precision    recall  f1-score   support

           2       0.98      0.96      0.97        45
           4       0.92      0.96      0.94        25

   micro avg       0.96      0.96      0.96        70
   macro avg       0.95      0.96      0.95        70
weighted avg       0.96      0.96      0.96        70


Evaluation on Fold #  7

Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {4: 22, 2: 48})


C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Training Accuracy: 0.9809220985691574
Test Accuracy: 0.9571428571428572
Confusion Matrix:
 [[47  1]
 [ 2 20]]
Training Classification Report:
               precision    recall  f1-score   support

           2       0.99      0.98      0.99       410
           4       0.97      0.98      0.97       219

   micro avg       0.98      0.98      0.98       629
   macro avg       0.98      0.98      0.98       629
weighted avg       0.98      0.98      0.98       629


Testing Classification Report:
               precision    recall  f1-score   support

           2       0.96      0.98      0.97        48
           4       0.95      0.91      0.93        22

   micro avg       0.96      0.96      0.96        70
   macro avg       0.96      0.94      0.95        70
weighted avg       0.96      0.96      0.96        70


Evaluation on Fold #  8

Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {2: 46, 4: 24})


C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Training Accuracy: 0.9777424483306836
Test Accuracy: 0.9857142857142858
Confusion Matrix:
 [[45  1]
 [ 0 24]]
Training Classification Report:
               precision    recall  f1-score   support

           2       0.98      0.98      0.98       412
           4       0.97      0.97      0.97       217

   micro avg       0.98      0.98      0.98       629
   macro avg       0.98      0.98      0.98       629
weighted avg       0.98      0.98      0.98       629


Testing Classification Report:
               precision    recall  f1-score   support

           2       1.00      0.98      0.99        46
           4       0.96      1.00      0.98        24

   micro avg       0.99      0.99      0.99        70
   macro avg       0.98      0.99      0.98        70
weighted avg       0.99      0.99      0.99        70


Evaluation on Fold #  9

Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {4: 27, 2: 43})


C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Training Accuracy: 0.9761526232114467
Test Accuracy: 0.9714285714285714
Confusion Matrix:
 [[43  0]
 [ 2 25]]
Training Classification Report:
               precision    recall  f1-score   support

           2       0.98      0.98      0.98       415
           4       0.96      0.97      0.97       214

   micro avg       0.98      0.98      0.98       629
   macro avg       0.97      0.97      0.97       629
weighted avg       0.98      0.98      0.98       629


Testing Classification Report:
               precision    recall  f1-score   support

           2       0.96      1.00      0.98        43
           4       1.00      0.93      0.96        27

   micro avg       0.97      0.97      0.97        70
   macro avg       0.98      0.96      0.97        70
weighted avg       0.97      0.97      0.97        70


Evaluation on Fold #  10

Train Data Distribution defaultdict(<class 'int'>, {'Class': 1})

Test Data Distribution defaultdict(<class 'int'>, {4: 28, 2: 41})


C:\Users\Ayesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Training Accuracy: 0.9746031746031746
Test Accuracy: 0.9855072463768116
Confusion Matrix:
 [[41  0]
 [ 1 27]]
Training Classification Report:
               precision    recall  f1-score   support

           2       0.98      0.98      0.98       417
           4       0.97      0.96      0.96       213

   micro avg       0.97      0.97      0.97       630
   macro avg       0.97      0.97      0.97       630
weighted avg       0.97      0.97      0.97       630


Testing Classification Report:
               precision    recall  f1-score   support

           2       0.98      1.00      0.99        41
           4       1.00      0.96      0.98        28

   micro avg       0.99      0.99      0.99        69
   macro avg       0.99      0.98      0.98        69
weighted avg       0.99      0.99      0.99        69

